### ISSUE TITLE
Converting Hours into days

### ISSUE THREAD

**Issue by macharpe** [cedriclam/dnswatcher#5]
Hello,
I would like to have the conversion of hours when it reaches 24h into days to give a friendly output. Also it would be nice to see the huge detailed number of seconds rounded to the closest integer:

E.g.: since 167h55m58.044423979s could be 6days 23h55min58s

Thanks,

**Comment by clamoriniere** [comment]
Should be easy :)

**Comment by cedriclam** [comment]
resolve #6 will be deliver in the next release.
